name: homease1
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.10+1
  google_fonts: ^6.2.1
  cupertino_icons: ^1.0.6
  sqflite: ^2.3.2
  path: ^1.9.0
  firebase_core: ^3.7.0
  provider: ^6.1.2
  cloud_firestore: ^5.4.5
  firebase_auth: ^5.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  assets :
    - assets/images/login/apple.svg
    - assets/images/login/google.svg
    - assets/images/login/facebook.svg
